'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web.EMR

    Partial Public Class AssesmentPerawat

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''pnlPatientList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPatientList As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''RadTabStrip2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadTabStrip2 As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''RadMultiPage2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMultiPage2 As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''RadPageView3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''calTgl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTgl As Global.QIS.Web.Calendar

        '''<summary>
        '''txtSearchPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearchPatient As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearchPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchPatient As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlDepartmentFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDepartmentFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlServiceUnit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlServiceUnit As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''grdTodayPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdTodayPatient As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadPageView4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlPatientRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPatientRecord As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''imgPBPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPBPatient As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblPBPatientName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPatientGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientGender As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBRegistrationDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBRegistrationDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBRegistrationTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBRegistrationTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBRegistrationNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBRegistrationNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBMRN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBMRN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPatientDOB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientDOB As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBServiceUnitName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBServiceUnitName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBServiceUnitID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBServiceUnitID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBTransactionNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBTransactionNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPhysicianName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPhysicianName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBBusinessPartnerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBBusinessPartnerName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RadTabStrip3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadTabStrip3 As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''RadMultiPage3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMultiPage3 As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''rpvAsesmenKeperawatan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvAsesmenKeperawatan As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlNurseAssesment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNurseAssesment As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnBack As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbtnNewSOAP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnNewSOAP As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbtnSaveSOAP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnSaveSOAP As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''grdNurseAssessment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdNurseAssessment As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''ddlAssessmentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAssessmentType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtPengkajianID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPengkajianID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlAsalInformasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAsalInformasi As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtAsalInformasiNama control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAsalInformasiNama As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlAsalInformasiHubungan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAsalInformasiHubungan As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''_pnlTriage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents _pnlTriage As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlKdTriage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlKdTriage As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''calTglDatang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTglDatang As Global.QIS.Web.Calendar

        '''<summary>
        '''txtJamDatang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJamDatang As Global.eWorld.UI.MaskedTextBox

        '''<summary>
        '''calTglLayan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTglLayan As Global.QIS.Web.Calendar

        '''<summary>
        '''txtJamLayan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJamLayan As Global.eWorld.UI.MaskedTextBox

        '''<summary>
        '''txtKeluhanUtama control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtKeluhanUtama As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRiwayatKeluhanSaatIni control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRiwayatKeluhanSaatIni As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rblIsRiwayatAlergi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsRiwayatAlergi As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''ddlJenisAlergi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlJenisAlergi As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtReaksiAlergi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReaksiAlergi As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlKesadaran control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlKesadaran As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtttvTekananDarah control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtttvTekananDarah As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtttvBeratBadan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtttvBeratBadan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtttvNadi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtttvNadi As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlttvNadiDenyut control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlttvNadiDenyut As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtttvTinggiBadan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtttvTinggiBadan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtttvSuhu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtttvSuhu As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtttvIndexMassaTubuh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtttvIndexMassaTubuh As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtttvPernafasan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtttvPernafasan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rblIsNyeri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsNyeri As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''rblNyeriSkala control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblNyeriSkala As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtNyeriLokasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNyeriLokasi As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNyeriDurasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNyeriDurasi As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNyeriSkala control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNyeriSkala As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlNyeriMetode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNyeriMetode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlNRS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNRS As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlNRS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNRS As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlWajah control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWajah As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlWajah control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlWajah As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlGerakBawah control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlGerakBawah As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlGerakBawah control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGerakBawah As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlAktivitas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAktivitas As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlTangis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTangis As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlTangis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTangis As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlBicara control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBicara As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlBicara control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBicara As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlPola control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPola As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlNapas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNapas As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlTungkai control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTungkai As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlSadar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSadar As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlGerakan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlGerakan As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlGerak control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGerak As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlKompensasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlKompensasi As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlNyeriKualitas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNyeriKualitas As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlNyeriKarakteristik control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNyeriKarakteristik As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlNyeriBerkurang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNyeriBerkurang As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtNyeriBerkurangKeterangan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNyeriBerkurangKeterangan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlNyeriBertambah control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlNyeriBertambah As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtNyeriBertambahKeterangan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNyeriBertambahKeterangan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlAktivitasMobilisasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAktivitasMobilisasi As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtKategoriResikoJatuh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtKategoriResikoJatuh As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rblIsDekubitas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsDekubitas As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''ddlStatusPsikologi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatusPsikologi As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtStatusPsikologiKeterangan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStatusPsikologiKeterangan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlStatusMental control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatusMental As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtStatusMentalKeterangan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStatusMentalKeterangan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlStatusPernikahan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatusPernikahan As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rblIsHubunganKeluargaBaik control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsHubunganKeluargaBaik As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''ddlStatusTempatTinggal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatusTempatTinggal As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rblIsBeribadahTeratur control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsBeribadahTeratur As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''ddlPekerjaan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPekerjaan As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlPenjaminBayar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPenjaminBayar As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlStatusGizi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatusGizi As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlSkorPerubahanBeratBadan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSkorPerubahanBeratBadan As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rblIsTidakNafsuMakan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsTidakNafsuMakan As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtSkorNutrisi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSkorNutrisi As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rblIsPerluKonsultasiGizi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsPerluKonsultasiGizi As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''rblIsHamil control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsHamil As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtHamilGravidKeterangan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHamilGravidKeterangan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHamilParaKeterangan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHamilParaKeterangan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHamilAbortusKeterangan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHamilAbortusKeterangan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rblIsBersediaMenerimaInformasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsBersediaMenerimaInformasi As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''rblIsHambatanEdukasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsHambatanEdukasi As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''chkIsHambatanPendengaran control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHambatanPendengaran As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsHambatanPenglihatan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHambatanPenglihatan As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsHambatanKognitif control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHambatanKognitif As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsHambatanFisik control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHambatanFisik As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsHambatanBudaya control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHambatanBudaya As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsHambatanEmosi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHambatanEmosi As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsHambatanBahasa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHambatanBahasa As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtHambatanLainnya control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHambatanLainnya As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlPendidikanPasien control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPendidikanPasien As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlBahasaPasien control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBahasaPasien As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtBahasaLainnya control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBahasaLainnya As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlAgamaPasien control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAgamaPasien As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtBudayaPasien control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBudayaPasien As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPerluPenterjemah control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPerluPenterjemah As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlCaraBelajarDisukai control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCaraBelajarDisukai As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkIsDiagnosa control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsDiagnosa As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsDietNutrisi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsDietNutrisi As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsTerapi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsTerapi As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsNyeri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsNyeri As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsAlatMedis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAlatMedis As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtInformasiDiinginkan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInformasiDiinginkan As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkKeluar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkKeluar As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlDisposisi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDisposisi As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''calTglDisposisi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTglDisposisi As Global.QIS.Web.Calendar

        '''<summary>
        '''txtJamDisposisi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJamDisposisi As Global.eWorld.UI.MaskedTextBox

        '''<summary>
        '''ddlKdnKlr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlKdnKlr As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlCrKlr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCrKlr As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkIsKIE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsKIE As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsObatPulang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsObatPulang As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsFotoRadiologi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsFotoRadiologi As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsLaboratorium control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsLaboratorium As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsEKG control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsEKG As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsKIEAPS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsKIEAPS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsTTDAPS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsTTDAPS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddlRoomCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRoomCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtReferToHospitalName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReferToHospitalName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rblIsDeath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblIsDeath As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''txtDeathTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDeathTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rpvKeperawatan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvKeperawatan As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''DataGrid1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataGrid1 As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''rpvCatatanPerawat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvCatatanPerawat As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlNurseNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlNurseNotes As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lbtnBackNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnBackNotes As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbtnNewNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnNewNotes As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbtnSaveNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnSaveNotes As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''grdNurseNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdNurseNotes As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''calTglCP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calTglCP As Global.QIS.Web.Calendar

        '''<summary>
        '''txtJamCP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtJamCP As Global.eWorld.UI.MaskedTextBox

        '''<summary>
        '''txtNurseNotesID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNurseNotesID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNurseNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNurseNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkIsPhysicianConfirmed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsPhysicianConfirmed As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''rpvCPPT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvCPPT As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlCPPT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCPPT As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdCatatanMedis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCatatanMedis As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdCatatanPerawat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCatatanPerawat As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdCatatanUnitLainnya control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCatatanUnitLainnya As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
