'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web.EMR

    Partial Public Class AssesmentMedis

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''pnlDashboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDashboard As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTotalPasienIGD control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalPasienIGD As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalPasienRawatJalan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalPasienRawatJalan As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalPasienRawatInap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalPasienRawatInap As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lbtnBackToPatientList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnBackToPatientList As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtLinkParamedicID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLinkParamedicID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkIsPhysician control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsPhysician As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''RadTabStrip1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadTabStrip1 As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''RadMultiPage1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMultiPage1 As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''RadPageView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView1 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''pnlPatientList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPatientList As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''RadTabStrip2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadTabStrip2 As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''RadMultiPage2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMultiPage2 As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''RadPageView3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView3 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''txtTodayDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTodayDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSearchPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearchPatient As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSearchPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchPatient As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlDepartmentFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDepartmentFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''grdTodayPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdTodayPatient As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadPageView4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView4 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''txtMedicalNoHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMedicalNoHistory As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnShowHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnShowHistory As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''imgPBPatientHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPBPatientHistory As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblPBPatientNameHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientNameHistory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPatientGenderHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientGenderHistory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBMRNHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBMRNHistory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBAddressHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBAddressHistory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPatientDOBHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientDOBHistory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdPatientResumeHistoryMR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatientResumeHistoryMR As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlPatientRecord control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPatientRecord As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''imgPBPatient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPBPatient As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblPBPatientName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPatientGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientGender As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBRegistrationDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBRegistrationDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBRegistrationTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBRegistrationTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBDepartmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBDepartmentName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBRegistrationNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBRegistrationNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBMRN control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBMRN As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPatientDOB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPatientDOB As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBServiceUnitName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBServiceUnitName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBServiceUnitID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBServiceUnitID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBTransactionNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBTransactionNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBPhysicianName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBPhysicianName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPBBusinessPartnerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPBBusinessPartnerName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''RadTabStrip3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadTabStrip3 As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''RadMultiPage3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMultiPage3 As Global.Telerik.Web.UI.RadMultiPage

        '''<summary>
        '''RadPageView5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView5 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''lbtnNewSOAP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnNewSOAP As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbtnSaveSOAP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnSaveSOAP As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbtnDischarge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnDischarge As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ddlAssessmentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAssessmentType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkIsDischarged control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsDischarged As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''txtChiefComplaint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtChiefComplaint As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHistoryOfPresentIllness control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHistoryOfPresentIllness As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtObjectiveText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtObjectiveText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMainDiagnosisText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMainDiagnosisText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSecondaryDiagnosisText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecondaryDiagnosisText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProcedureText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProcedureText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkIsCreateOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsCreateOrder As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkIsRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsRealized As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTherapyHISOrderNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTherapyHISOrderNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTherapyText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTherapyText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMeasurableTargetText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMeasurableTargetText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTherapyStopDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTherapyStopDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnGenerateSOAPNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnGenerateSOAPNotes As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtSOAPNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSOAPNotes As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdPatientResume control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatientResume As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadPageView10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView10 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''grdPatientResumeHistory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatientResumeHistory As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadPageView6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView6 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''grdPatientDocument control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatientDocument As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdPatientDocumentByRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatientDocumentByRegistration As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadPageView7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView7 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''lbtnNewIE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnNewIE As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lbtnSaveIE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnSaveIE As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtIDIE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIDIE As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtComplainTextIE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtComplainTextIE As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtInterventionTextIE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInterventionTextIE As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEvaluationTextIE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEvaluationTextIE As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdPatientInterventionEvaluation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatientInterventionEvaluation As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadComboBox2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadComboBox2 As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''DropDownList3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownList3 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''Button3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Button3 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''DataGrid3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataGrid3 As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadPageView8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView8 As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''grdCatatanMedis control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCatatanMedis As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdCatatanPerawatNurseNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCatatanPerawatNurseNotes As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdCatatanPerawat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCatatanPerawat As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdCatatanUnitLainnya control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdCatatanUnitLainnya As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''RadPageView2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadPageView2 As Global.Telerik.Web.UI.RadPageView
    End Class
End Namespace
