'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web.Secure

    Partial Public Class BudgetPurchasing

        '''<summary>
        '''frm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''lblPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ibtnEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnEdit As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ibtnMapping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnMapping As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ibtnRealisasi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnRealisasi As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''pnlBudgetSetting control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBudgetSetting As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''txtBudgetPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBudgetPeriod As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtBudgetCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBudgetCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtUnitPrice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUnitPrice As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtBudgetName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBudgetName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtQuantity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuantity As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlPurchaseOrderType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPurchaseOrderType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rcbLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbLocation As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''rcbAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbAccount As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''grdBudgetPurchasing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdBudgetPurchasing As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlBudgetMapping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBudgetMapping As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlYearInBudget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlYearInBudget As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlMataAnggaranMapping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMataAnggaranMapping As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''grdItemGroupExMapping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdItemGroupExMapping As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRemove As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdItemGroupInMapping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdItemGroupInMapping As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlBudgetRealizations control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBudgetRealizations As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlBudgetPeriodRealization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlBudgetPeriodRealization As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rcbLocationRealization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbLocationRealization As Global.Telerik.Web.UI.RadComboBox

        '''<summary>
        '''grdBudgetPurchasingRealization control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdBudgetPurchasingRealization As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
