'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web.Secure

    Partial Public Class DrugInteractionInfo

        '''<summary>
        '''frm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''ibtnDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnDetail As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ibtnEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnEdit As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''pnlInteraksiObat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInteraksiObat As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''ValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''txtGenericName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGenericName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvGenericName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvGenericName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''lblGenericName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGenericName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblGenericGroupName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGenericGroupName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblBrandName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBrandName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInteractionDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInteractionDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSearchObat1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchObat1 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSearchObat2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchObat2 As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCheckInteraction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCheckInteraction As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtItemCode1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemCode1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtItemName1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemName1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtItemCode2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemCode2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtItemName2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemName2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblCheckInteractionResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCheckInteractionResult As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlEditInteraksiObat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEditInteraksiObat As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ValidationSummaryEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummaryEdit As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''txtDrugInteractionHdID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDrugInteractionHdID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtGenericNameEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGenericNameEdit As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtGenericGroupName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGenericGroupName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtBrandNames control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBrandNames As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtInteractionDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInteractionDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSaveInteraksi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveInteraksi As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNewInteraksi control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewInteraksi As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''ddlGenericNameList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlGenericNameList As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtInteractionDescriptionDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtInteractionDescriptionDt As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSaveDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveDt As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdDrugInteractionDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdDrugInteractionDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''btnSearchObat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSearchObat As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtItemCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtItemName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnAddDrugGenericMtx control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddDrugGenericMtx As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdDrugGenericMtx control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdDrugGenericMtx As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdDrugInteractionHd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdDrugInteractionHd As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
