'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web

    Partial Public Class IncidentInvestigation

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''txtYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtYear As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdIncidentInvestigation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdIncidentInvestigation As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''lblCreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReviewBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReviewBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtReportNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkIsApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsApproved As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''calReportDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calReportDate As Global.QIS.Web.Calendar

        '''<summary>
        '''txtincidentSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtincidentLocation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentLocation As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''calincidentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calincidentDate As Global.QIS.Web.Calendar

        '''<summary>
        '''txtincidentTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlseveritySCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlseveritySCode As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnIncidentInvestigation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnIncidentInvestigation As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnIncidentChronological control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnIncidentChronological As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlInvestigation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInvestigation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtincidentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentType As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtincidentDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtincidentWitness control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentWitness As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtincidentConsequence control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentConsequence As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtincidentConsequenceEst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentConsequenceEst As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtincidentTrigger control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtincidentTrigger As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtcorrectiveAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcorrectiveAction As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtrecommendationFromDeptMgr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtrecommendationFromDeptMgr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlChronological control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlChronological As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''btnAddIncidentChronological control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddIncidentChronological As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''calChronologicalDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calChronologicalDate As Global.QIS.Web.Calendar

        '''<summary>
        '''txtChronologicalTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtChronologicalTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtIncidentChronological control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIncidentChronological As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdIncidentChronological control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdIncidentChronological As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
