'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web

    Partial Public Class Planned

        '''<summary>
        '''Head1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''ibtnMyProjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnMyProjects As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnMyProjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnMyProjects As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnMyDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnMyDay As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnMyDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnMyDay As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnUrgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnUrgents As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnUrgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnUrgents As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblUrgentsTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUrgentsTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ibtnPlanned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnPlanned As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnPlanned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnPlanned As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnMyAssignments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnMyAssignments As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnMyAssignments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnMyAssignments As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblAssignmentsTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAssignmentsTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ibtnFollowUpIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnFollowUpIssue As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnFollowUpIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnFollowUpIssue As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnIssueStudy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnIssueStudy As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnIssueStudy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnIssueStudy As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''calStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calStartDate As Global.QIS.Web.Calendar

        '''<summary>
        '''calEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calEndDate As Global.QIS.Web.Calendar

        '''<summary>
        '''ddlProjectGroupFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProjectGroupFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkIsAssignedToMe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsAssignedToMe As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddlIssueStatusFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueStatusFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblTotalIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalIssue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalOpen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalOpen As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalInProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalInProgress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalDevFinish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalDevFinish As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalQCPassed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalQCPassed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalFinish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalFinish As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProgress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddNew As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblIssueID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIssueID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDepartmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDepartmentName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvDepartmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvDepartmentName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtIssueDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIssueDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvIssueDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvIssueDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtKeywords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtKeywords As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''calReportedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calReportedDate As Global.QIS.Web.Calendar

        '''<summary>
        '''txtReportedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportedBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlIssueType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssuePriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssuePriority As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlUserIDAssignedTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUserIDAssignedTo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssueStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssueConfirmStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueConfirmStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnSaveAndNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveAndNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSaveAndClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveAndClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''repIssueFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents repIssueFile As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlIssueResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlIssueResponse As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Response_lblIssueID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblIssueID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_lblDepartmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblDepartmentName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_lblIssueDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblIssueDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_calResponseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_calResponseDate As Global.QIS.Web.Calendar

        '''<summary>
        '''Response_txtResponseDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_txtResponseDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Response_rfvResponseDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_rfvResponseDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Response_lblResponseID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblResponseID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_btnSaveAndNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_btnSaveAndNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Response_btnSaveAndClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_btnSaveAndClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Response_btnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdIssueResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdIssueResponse As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdIssueByFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdIssueByFilter As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
