'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web

    Partial Public Class PrintTicket

        '''<summary>
        '''issueid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents issueid As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''projectaliasname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents projectaliasname As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''userIDprint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents userIDprint As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''projectName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents projectName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''reportedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reportedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''departmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents departmentName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''reportedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents reportedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''issueDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents issueDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''targetdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents targetdate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''issuePriorityName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents issuePriorityName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''issueStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents issueStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''issueType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents issueType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''issueConfirmStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents issueConfirmStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdPrintIssueResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPrintIssueResponse As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''datenow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents datenow As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''userprint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents userprint As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''medinfrasteam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents medinfrasteam As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
