'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web

    Partial Public Class Print

        '''<summary>
        '''projectid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents projectid As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''projectnama control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents projectnama As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''time control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents time As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''totalreported control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents totalreported As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''totalfinished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents totalfinished As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''openissue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents openissue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''progressissue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents progressissue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''finishissue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents finishissue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''needsampleissue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents needsampleissue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''devfinish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents devfinish As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''totalissuefull control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents totalissuefull As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''overallprogress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents overallprogress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdPrintIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPrintIssue As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
