'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web.Secure

    Partial Public Class Progress

        '''<summary>
        '''frm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''ddlPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPeriod As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlCustomPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCustomPeriod As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''calStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calStartDate As Global.QIS.Web.Calendar

        '''<summary>
        '''calEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calEndDate As Global.QIS.Web.Calendar

        '''<summary>
        '''pnlDailyActivity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDailyActivity As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''repProgressPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents repProgressPeriod As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlActivityByPeople control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlActivityByPeople As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdUser As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
