'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web

    Partial Public Class ProjectTimeline

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''ibtnMyProjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnMyProjects As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnMyProjects control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnMyProjects As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnMyDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnMyDay As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnMyDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnMyDay As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnUrgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnUrgents As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnUrgents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnUrgents As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblUrgentsTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUrgentsTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ibtnPlanned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnPlanned As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnPlanned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnPlanned As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnMyAssignments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnMyAssignments As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnMyAssignments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnMyAssignments As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblAssignmentsTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAssignmentsTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ibtnFollowUpIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnFollowUpIssue As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnFollowUpIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnFollowUpIssue As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''ibtnIssueStudy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnIssueStudy As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''lbtnIssueStudy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtnIssueStudy As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''lblProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectAliasName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectAliasName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblLastPatchNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastPatchNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectLastUpdatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectLastUpdatedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectCreatedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddNew As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblProjectTimelineID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectTimelineID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvSequenceNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtPredecessorSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPredecessorSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTask As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''calStartDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calStartDateScheduled As Global.QIS.Web.Calendar

        '''<summary>
        '''txtStartTimeScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartTimeScheduled As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''calEndDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calEndDateScheduled As Global.QIS.Web.Calendar

        '''<summary>
        '''txtEndTimeScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndTimeScheduled As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTaskDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTaskDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlUserIDPIC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUserIDPIC As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlTaskStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTaskStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''calStartDateRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calStartDateRealized As Global.QIS.Web.Calendar

        '''<summary>
        '''txtStartTimeRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStartTimeRealized As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''calEndDateRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calEndDateRealized As Global.QIS.Web.Calendar

        '''<summary>
        '''txtEndTimeRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndTimeRealized As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnSaveOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveOnly As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSaveAndNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveAndNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSaveAndClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveAndClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlSubTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSubTask As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''SubTask_lblProjectTimelineID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblProjectTimelineID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_lblSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblSequenceNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_lblStartDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblStartDateScheduled As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_lblStartDateRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblStartDateRealized As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_lblTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblTask As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_lblEndDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblEndDateScheduled As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_lblEndDateRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblEndDateRealized As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_lblProjectTimelineSubTaskID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_lblProjectTimelineSubTaskID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SubTask_txtSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_txtSequenceNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubTask_rfvSequenceNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_rfvSequenceNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''SubTask_txtSubTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_txtSubTask As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubTask_calStartDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_calStartDateScheduled As Global.QIS.Web.Calendar

        '''<summary>
        '''SubTask_txtStartTimeScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_txtStartTimeScheduled As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubTask_calEndDateScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_calEndDateScheduled As Global.QIS.Web.Calendar

        '''<summary>
        '''SubTask_txtEndTimeScheduled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_txtEndTimeScheduled As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubTask_txtSubTaskDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_txtSubTaskDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubTask_ddlUserIDPIC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_ddlUserIDPIC As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SubTask_ddlSubTaskStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_ddlSubTaskStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''SubTask_calStartDateRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_calStartDateRealized As Global.QIS.Web.Calendar

        '''<summary>
        '''SubTask_txtStartTimeRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_txtStartTimeRealized As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubTask_calEndDateRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_calEndDateRealized As Global.QIS.Web.Calendar

        '''<summary>
        '''SubTask_txtEndTimeRealized control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_txtEndTimeRealized As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SubTask_btnSaveAndNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_btnSaveAndNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SubTask_btnSaveAndClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_btnSaveAndClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SubTask_btnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubTask_btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdProjectTimelineSubTask control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdProjectTimelineSubTask As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdProjectTimeline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdProjectTimeline As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
