'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web.Secure

    Partial Public Class Project

        '''<summary>
        '''frm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frm As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''ValidationSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ValidationSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''txtProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProjectAliasName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectAliasName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvProjectAliasName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvProjectAliasName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtProjectName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtProjectDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProjectDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlProjectStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProjectStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlProjectGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProjectGroup As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtHEXColorID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHEXColorID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''chkIsOpenForClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsOpenForClient As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''grdProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdProfile As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''btnProfileProjectAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProfileProjectAdd As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnProfileProjectAddAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProfileProjectAddAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnProfileProjectRemoveAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProfileProjectRemoveAll As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnProfileProjectRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnProfileProjectRemove As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdProjectProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdProjectProfile As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdProject As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
