'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web.PatchManagement

    Partial Public Class PatchList

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''txtSelectPatchNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSelectPatchNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''grdPatchList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatchList As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''lblPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''txtPatchNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPatchNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgIsClosed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgIsClosed As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblClosedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClosedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblClosedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClosedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''calPatchDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calPatchDate As Global.QIS.Web.Calendar

        '''<summary>
        '''txtRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''pnlAddNewPatchIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddNewPatchIssue As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtIssueID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIssueID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvIssueID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvIssueID As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''chkIsSpecific control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsSpecific As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblIssueInformation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIssueInformation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlIssuePatchWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlIssuePatchWarning As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblIssueAlreadyOnOtherPatch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIssueAlreadyOnOtherPatch As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnAddPatchIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddPatchIssue As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdPatchIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatchIssue As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlAddNewPatchDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddNewPatchDt As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PatchDt_txtPatchDtID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchDt_txtPatchDtID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PatchDt_txtRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchDt_txtRemarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PatchDt_rfvtxtRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchDt_rfvtxtRemarks As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''PatchDt_ddlProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchDt_ddlProject As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''PatchDt_chkIsSpecific control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchDt_chkIsSpecific As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''PatchDt_btnAddPatchDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchDt_btnAddPatchDt As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdPatchDt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatchDt As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlAddNewRowPatchProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddNewRowPatchProject As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''PatchProject_txtPatchProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchProject_txtPatchProjectID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PatchProject_ddlProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchProject_ddlProject As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''PatchProject_calUpdateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchProject_calUpdateDate As Global.QIS.Web.Calendar

        '''<summary>
        '''PatchProject_txtRemarks control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchProject_txtRemarks As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''PatchProject_btnAddPatchProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PatchProject_btnAddPatchProject As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdPatchProject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdPatchProject As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
