'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace QIS.Web

    Partial Public Class CustomerMain

        '''<summary>
        '''Form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''RadMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents RadMenu As Global.QIS.RadMenu

        '''<summary>
        '''lblPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPageTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ibtnViewDashboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnViewDashboard As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ibtnViewDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ibtnViewDetail As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''CSSToolbar control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CSSToolbar As Global.QIS.CSSToolbar

        '''<summary>
        '''lblTotalIssueAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalIssueAll As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalOpen control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalOpen As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalCRFQuotation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCRFQuotation As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalInProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalInProgress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalDevFinish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalDevFinish As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalFinish control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalFinish As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCancel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProgress As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalOpenPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalOpenPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalCRFQuotationPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCRFQuotationPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalInProgressPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalInProgressPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalDevFinishPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalDevFinishPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalFinishPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalFinishPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalCancelPct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalCancelPct As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblTotalIssue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotalIssue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlProjectFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProjectFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkIsFilterByPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsFilterByPeriod As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlCustomPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCustomPeriod As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''calStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calStartDate As Global.QIS.Web.Calendar

        '''<summary>
        '''calEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calEndDate As Global.QIS.Web.Calendar

        '''<summary>
        '''lblLastPatchNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastPatchNo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkIsOpenForClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsOpenForClient As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''ddlProductRoadmapFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlProductRoadmapFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssueStatusFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueStatusFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlUserIDAssignedToFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUserIDAssignedToFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssueConfirmStatusFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueConfirmStatusFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssuePriorityFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssuePriorityFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssueTypeFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueTypeFilter As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkIsUrgent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsUrgent As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''pnlAddNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAddNew As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblIssueID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIssueID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProjectID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProjectID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtDepartmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDepartmentName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvDepartmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvDepartmentName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtIssueDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIssueDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rfvIssueDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvIssueDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''txtKeywords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtKeywords As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblReportedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReportedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''calReportedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents calReportedDate As Global.QIS.Web.Calendar

        '''<summary>
        '''txtReportedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReportedBy As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlIssueType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssuePriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssuePriority As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlUserIDAssignedTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUserIDAssignedTo As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssueStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''ddlIssueConfirmStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlIssueConfirmStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSaveAndNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveAndNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSaveAndClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSaveAndClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''txtIssueFileID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIssueFileID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtIssueFileUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIssueFileUrl As Global.System.Web.UI.HtmlControls.HtmlInputFile

        '''<summary>
        '''txtIssueFileDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIssueFileDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtIssueFileName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtIssueFileName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnIssueFileAttach control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnIssueFileAttach As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''repIssueFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents repIssueFile As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''pnlIssueResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlIssueResponse As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''Response_lblIssueID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblIssueID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_lblDepartmentName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblDepartmentName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_lblIssueDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblIssueDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_calResponseDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_calResponseDate As Global.QIS.Web.Calendar

        '''<summary>
        '''Response_txtResponseDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_txtResponseDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Response_rfvResponseDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_rfvResponseDescription As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''Response_lblResponseID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_lblResponseID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Response_btnSaveAndNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_btnSaveAndNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Response_btnSaveAndClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_btnSaveAndClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''Response_btnClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Response_btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdIssueResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdIssueResponse As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''grdIssueByFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdIssueByFilter As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''mdlCopyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mdlCopyRight As Global.QIS.Web.copyRight
    End Class
End Namespace
